/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AmcRouteImport } from './routes/amc'
import { Route as IndexRouteImport } from './routes/index'

const AmcRoute = AmcRouteImport.update({
  id: '/amc',
  path: '/amc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amc': typeof AmcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amc': typeof AmcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amc': typeof AmcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/amc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/amc'
  id: '__root__' | '/' | '/amc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmcRoute: typeof AmcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/amc': {
      id: '/amc'
      path: '/amc'
      fullPath: '/amc'
      preLoaderRoute: typeof AmcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmcRoute: AmcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
